name: ðŸš¥ Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for server
        run: npm install
        working-directory: server
      - name: Run tests on server
        run: npm run test
        working-directory: server
      - name: Run lint on server
        run: npm run lint
        working-directory: server
      - name: Install dependencies for client
        run: npm install
        working-directory: client
      - name: Run lint on client
        run: npm run lint
        working-directory: client
      - name: Run tests for client
        run: npm run test
        working-directory: client